-- ═══════════════════════════════════════════════════════════════
-- 045: Add `source` column to user_exercises
--
-- Tracks whether an exercise was created manually by the user ('user')
-- or auto-generated by the AI plan generator ('ai').
-- The exercise_creator achievement only counts 'user' exercises,
-- preventing instant legendary from a single AI plan import.
-- ═══════════════════════════════════════════════════════════════

alter table public.user_exercises
  add column if not exists source text not null default 'user'
  check (source in ('user', 'ai'));

comment on column public.user_exercises.source is
  'Origin of the exercise: user (manually created) or ai (AI plan generator).';
